# Generated by Django 5.2.7 on 2025-10-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_activo_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
